#pragma once
#include <stdint.h>

// ─── SmallFont: 2-bit AA bitmap font (4px/byte, MSB-first) ───────────────────
// Generated by tools/gen_small_font.py. Do not edit manually.

struct SmallGlyph {
  uint16_t bitmapOffset;  // byte offset into bitmap array
  uint8_t  width, height;
  uint8_t  xAdvance;
  int8_t   xOffset, yOffset;  // relative to cursor (yOffset: negative = above baseline)
};

struct SmallFont {
  const uint8_t*    bitmap;   // 2bpp PROGMEM: 4px/byte, MSB-first
  const SmallGlyph* glyphs;   // PROGMEM
  uint8_t  first, last;
  uint8_t  yAdvance;
};

// Draw ASCII string at (x, baseline). Returns x after last glyph.
int16_t  printSmall(const SmallFont* f, const char* s, int16_t x, int16_t baseline,
                    uint16_t fg, uint16_t bg);

// Total advance width of string in pixels.
uint16_t smallTextWidth(const SmallFont* f, const char* s);
