#pragma once
#include "display.h"

// ─── Font metrics (SF Mono 19pt, 2-bit AA) ───────────────────────────────────
// Auto-generated by tools/gen_font.py — do not change manually.
#define UA_ADVANCE  12   // xAdvance per character
#define UA_ASCENT   18   // pixels above baseline
#define UA_DESCENT   3   // pixels below baseline

// ─── printUA ─────────────────────────────────────────────────────────────────
// Draws a UTF-8 string at the current cursor position (cursor Y = baseline).
// Each UA_ADVANCE-wide cell is erased with 'bg' before drawing (flicker-free).
void printUA(const char* str, uint16_t fg, uint16_t bg);

// ─── printUAn ────────────────────────────────────────────────────────────────
// Draws exactly n codepoints from str, starting at codepoint offset skip.
// If the string has fewer than skip+n codepoints, trailing spaces are drawn.
void printUAn(const char* str, uint8_t skip, uint8_t n, uint16_t fg, uint16_t bg);
