#!/usr/bin/env python3
"""
Generate a SmallFont 2-bit AA bitmap font header from a TTF.
Usage: python3 gen_small_font.py
Outputs: ../FreeSans7pt7b.h
"""
from PIL import Image, ImageDraw, ImageFont
import os

FONT_PATH = "/System/Library/Fonts/Supplemental/Arial.ttf"
FONT_SIZE  = 13          # cap height ~10px
OUT_NAME   = "FreeSans7pt7b"
OUT_FILE   = os.path.join(os.path.dirname(__file__), "..", f"{OUT_NAME}.h")
FIRST_CHAR = 0x20
LAST_CHAR  = 0x7E

font = ImageFont.truetype(FONT_PATH, FONT_SIZE)
ascent, descent = font.getmetrics()

# ─── render one character → (rows of grayscale, w, h, xoff, yoff, xadvance) ──
def render_char(ch):
    img = Image.new("L", (80, 80), 0)
    draw = ImageDraw.Draw(img)
    draw.text((20, 20), ch, font=font, fill=255)

    arr = img.load()
    xs, ys = [], []
    for y in range(80):
        for x in range(80):
            if arr[x, y] > 32:
                xs.append(x); ys.append(y)

    if not xs:
        advance = int(font.getlength(" ")) if ch == " " else 1
        return [], 0, 0, 0, 1, advance

    x0, x1 = min(xs), max(xs)
    y0, y1 = min(ys), max(ys)
    w = x1 - x0 + 1
    h = y1 - y0 + 1

    baseline_y = 20 + ascent
    glyph_xoff = x0 - 20
    y_offset_gfx = y0 - baseline_y

    advance = round(font.getlength(ch))

    rows = []
    for y in range(y0, y1 + 1):
        row = []
        for x in range(x0, x1 + 1):
            row.append(arr[x, y])  # grayscale 0..255
        rows.append(row)

    return rows, w, h, glyph_xoff, y_offset_gfx, advance


# ─── map grayscale 0..255 → 2-bit level 0..3 ─────────────────────────────────
def to_level(v):
    if v < 64:  return 0
    if v < 128: return 1
    if v < 192: return 2
    return 3


# ─── pack glyph pixels as 2bpp, 4px/byte, MSB-first, padded to byte boundary ──
def pack_glyph_2bpp(rows):
    pixels = []
    for row in rows:
        for p in row:
            pixels.append(to_level(p))
    while len(pixels) % 4:
        pixels.append(0)
    out = []
    for i in range(0, len(pixels), 4):
        byte = (pixels[i] << 6) | (pixels[i+1] << 4) | (pixels[i+2] << 2) | pixels[i+3]
        out.append(byte)
    return out


# ─── collect all glyphs ───────────────────────────────────────────────────────
all_bitmap_bytes = []
glyphs = []  # (offset, w, h, xAdv, xOff, yOff)

for code in range(FIRST_CHAR, LAST_CHAR + 1):
    ch = chr(code)
    rows, w, h, xoff, yoff, adv = render_char(ch)

    offset = len(all_bitmap_bytes)
    if w == 0 or h == 0:
        glyphs.append((offset, 0, 0, adv, 0, 1))
    else:
        packed = pack_glyph_2bpp(rows)
        all_bitmap_bytes.extend(packed)
        glyphs.append((offset, w, h, adv, xoff, yoff))

y_advance = ascent + descent + 2

_, _, cap_h, _, cap_yoff, _ = render_char("H")
print(f"H: cap_height={cap_h}, yOffset={cap_yoff}")
print(f"ascent={ascent}, descent={descent}, yAdvance={y_advance}")
print(f"Total bitmap bytes: {len(all_bitmap_bytes)}")

# ─── write header ─────────────────────────────────────────────────────────────
lines = []
lines.append(f"#pragma once")
lines.append(f"#include \"smallprint.h\"")
lines.append(f"")
lines.append(f"// 2-bit AA bitmap font (Arial {FONT_SIZE}px, cap height {cap_h}px)")
lines.append(f"// Generated by tools/gen_small_font.py — do not edit manually.")
lines.append(f"")
lines.append(f"static const uint8_t {OUT_NAME}Bitmaps[] PROGMEM = {{")
for i in range(0, len(all_bitmap_bytes), 12):
    chunk = all_bitmap_bytes[i:i+12]
    lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
lines.append(f"}};")
lines.append(f"")
lines.append(f"static const SmallGlyph {OUT_NAME}Glyphs[] PROGMEM = {{")
for i, (off, w, h, adv, xoff, yoff) in enumerate(glyphs):
    ch = chr(FIRST_CHAR + i)
    comment = f"// 0x{FIRST_CHAR+i:02X} '{ch}'" if ch.isprintable() else f"// 0x{FIRST_CHAR+i:02X}"
    lines.append(f"    {{{off}, {w}, {h}, {adv}, {xoff}, {yoff}}},  {comment}")
lines.append(f"}};")
lines.append(f"")
lines.append(f"static const SmallFont {OUT_NAME} = {{")
lines.append(f"    {OUT_NAME}Bitmaps, {OUT_NAME}Glyphs,")
lines.append(f"    0x{FIRST_CHAR:02X}, 0x{LAST_CHAR:02X}, {y_advance}}};")
lines.append(f"")
lines.append(f"// {len(all_bitmap_bytes) + len(glyphs)*6 + 8} bytes total")

with open(OUT_FILE, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"Written: {OUT_FILE}")
